server:
  port: 8087
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zilongkuaikan?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  mail:
    host: smtp.qq.com
    username: 1819877370@qq.com
    password: aapqgpehglwoedia
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.qf.pojo

qiniu:
  ak: m7mFmCTX55PMNPkEBaOLFQMLxW4ZFfZwf2EBm1M2
  sk: dn220PqIs813-IYrIZtzO_bGLXPo3QSVNep6wNty
  bucket: qf-2007
  url: http://qk18e4f7p.hb-bkt.clouddn.com/